CREATE TABLE `consignment_approval` (
   `id` int NOT NULL AUTO_INCREMENT,
   `cn_no` varchar(20) NOT NULL,
   `shipper_code` varchar(20) NOT NULL,
   `shipper_name` varchar(100) DEFAULT NULL,
   `receiver_name` varchar(50) NOT NULL,
   `driver_name` varchar(50) NOT NULL DEFAULT '',
   `destination_code` varchar(20) DEFAULT NULL,
   `region` varchar(20) NOT NULL DEFAULT 'HQ',
   `cn_datetime` datetime NOT NULL,
   `delivery_no` varchar(20) DEFAULT NULL,
   `quantity` varchar(20) NOT NULL DEFAULT '1',
   `measure` varchar(20) DEFAULT NULL,
   `weight` varchar(20) DEFAULT NULL,
   `carton_size` int DEFAULT '0',
   `carton_rate` varchar(20) DEFAULT NULL,
   `m3_size` int NOT NULL DEFAULT '0',
   `m3_rate` varchar(20) DEFAULT NULL,
   `pallet_size` int NOT NULL DEFAULT '0',
   `pallet_rate` varchar(20) DEFAULT NULL,
   `s_size` int NOT NULL DEFAULT '0',
   `s_rate` varchar(20) DEFAULT NULL,
   `m_size` int NOT NULL DEFAULT '0',
   `m_rate` varchar(20) DEFAULT NULL,
   `l_size` int NOT NULL DEFAULT '0',
   `l_rate` varchar(20) DEFAULT NULL,
   `xl_size` int NOT NULL DEFAULT '0',
   `xl_rate` varchar(20) DEFAULT NULL,
   `pkt_size` int NOT NULL DEFAULT '0',
   `pkt_rate` varchar(20) DEFAULT NULL,
   `other_charges` int NOT NULL DEFAULT '0',
   `other_amount` varchar(20) DEFAULT NULL,
   `sub_amount` varchar(20) DEFAULT NULL,
   `tax_amount` varchar(20) DEFAULT NULL,
   `total_amount` varchar(20) DEFAULT NULL,
   `invoice_no` varchar(20) NOT NULL,
   `created_on` timestamp NULL DEFAULT NULL,
   `created_by` varchar(20) DEFAULT NULL,
   `changed_on` timestamp NULL DEFAULT NULL,
   `changed_by` varchar(20) DEFAULT NULL,
   `status` varchar(20) NOT NULL DEFAULT 'created',
   `remarks` varchar(50) DEFAULT NULL,
   `receiver_code` varchar(20) NOT NULL,
   `m3_min_size` int NOT NULL DEFAULT '0',
   `m3_min_rate` varchar(20) DEFAULT NULL,
   `weight_min_size` int NOT NULL DEFAULT '0',
   `weight_min_rate` varchar(20) DEFAULT NULL,
   `weight_size` int NOT NULL DEFAULT '0',
   `weight_rate` varchar(20) DEFAULT NULL,
   `is_billed` tinyint(1) NOT NULL DEFAULT '0',
   `p_size` int NOT NULL DEFAULT '0',
   `p_rate` varchar(20) DEFAULT NULL,
   PRIMARY KEY (`id`)
 ) ENGINE=InnoDB  DEFAULT CHARSET=latin1